// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#ifndef UI_SCREENWIFI_H
#define UI_SCREENWIFI_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenWiFi
extern void ui_ScreenWiFi_screen_init(void);
extern void ui_ScreenWiFi_screen_destroy(void);
extern void ui_event_ScreenWiFi( lv_event_t * e);
extern lv_obj_t *ui_ScreenWiFi;
extern lv_obj_t *ui_Container1;
extern lv_obj_t *ui_LabelSSID;
extern lv_obj_t *ui_LabelWiFiStatus;
extern lv_obj_t *ui_LabelWiFiIP;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

