// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#ifndef UI_SCREENSPLASH_H
#define UI_SCREENSPLASH_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenSplash
extern void ui_ScreenSplash_screen_init(void);
extern void ui_ScreenSplash_screen_destroy(void);
extern void ui_event_ScreenSplash( lv_event_t * e);
extern lv_obj_t *ui_ScreenSplash;
extern lv_obj_t *ui_SplashContainer;
extern lv_obj_t *ui_NameLabel;
extern lv_obj_t *ui_VersionLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

