// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#ifndef UI_SCREENCLOCK_H
#define UI_SCREENCLOCK_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenClock
extern void ui_ScreenClock_screen_init(void);
extern void ui_ScreenClock_screen_destroy(void);
extern void ui_event_ScreenClock( lv_event_t * e);
extern lv_obj_t *ui_ScreenClock;
extern lv_obj_t *ui_Container2;
extern lv_obj_t *ui_Label1;
extern lv_obj_t *ui_Label2;
extern lv_obj_t *ui_Label3;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

