// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#include "../ui.h"

lv_obj_t *ui_ScreenSplash = NULL;lv_obj_t *ui_SplashContainer = NULL;lv_obj_t *ui_NameLabel = NULL;lv_obj_t *ui_VersionLabel = NULL;
// event funtions
void ui_event_ScreenSplash( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_ScreenClock, LV_SCR_LOAD_ANIM_OUT_RIGHT, 500, 5000, &ui_ScreenClock_screen_init);
}
}

// build funtions

void ui_ScreenSplash_screen_init(void)
{
ui_ScreenSplash = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSplash, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenSplash,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ScreenSplash, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_ScreenSplash, lv_color_hex(0x1B0674), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenSplash, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_SplashContainer = lv_obj_create(ui_ScreenSplash);
lv_obj_remove_style_all(ui_SplashContainer);
lv_obj_set_width( ui_SplashContainer, LV_SIZE_CONTENT);  /// 31
lv_obj_set_height( ui_SplashContainer, LV_SIZE_CONTENT);   /// 29
lv_obj_set_align( ui_SplashContainer, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_SplashContainer,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_SplashContainer, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_SplashContainer, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_SplashContainer, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_SplashContainer, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_NameLabel = lv_label_create(ui_SplashContainer);
lv_obj_set_width( ui_NameLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_NameLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_NameLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_NameLabel,"osName");
lv_obj_set_style_text_color(ui_NameLabel, lv_color_hex(0x3EE1DA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_NameLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_NameLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_VersionLabel = lv_label_create(ui_SplashContainer);
lv_obj_set_width( ui_VersionLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_VersionLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_VersionLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_VersionLabel,"osVersion");
lv_obj_set_style_text_color(ui_VersionLabel, lv_color_hex(0x3EE1DA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_VersionLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_VersionLabel, &lv_font_montserrat_26, LV_PART_MAIN| LV_STATE_DEFAULT);

lv_obj_add_event_cb(ui_ScreenSplash, ui_event_ScreenSplash, LV_EVENT_ALL, NULL);

}

void ui_ScreenSplash_screen_destroy(void)
{
   if (ui_ScreenSplash) lv_obj_del(ui_ScreenSplash);

// NULL screen variables
ui_ScreenSplash= NULL;
ui_SplashContainer= NULL;
ui_NameLabel= NULL;
ui_VersionLabel= NULL;

}
