// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#ifndef UI_SCREENDEBUG_H
#define UI_SCREENDEBUG_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_ScreenDebug
extern void ui_ScreenDebug_screen_init(void);
extern void ui_ScreenDebug_screen_destroy(void);
extern lv_obj_t *ui_ScreenDebug;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_DebugLineLabel;
extern lv_obj_t *ui_DebugLineLabel1;
extern lv_obj_t *ui_DebugLineLabel2;
extern lv_obj_t *ui_DebugLineLabel3;
extern lv_obj_t *ui_DebugLineLabel4;
extern lv_obj_t *ui_DebugLineLabel5;
extern lv_obj_t *ui_DebugLineLabel6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

