// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#include "../ui.h"

lv_obj_t *ui_ScreenDebug = NULL;lv_obj_t *ui_Container3 = NULL;lv_obj_t *ui_DebugLineLabel = NULL;lv_obj_t *ui_DebugLineLabel1 = NULL;lv_obj_t *ui_DebugLineLabel2 = NULL;lv_obj_t *ui_DebugLineLabel3 = NULL;lv_obj_t *ui_DebugLineLabel4 = NULL;lv_obj_t *ui_DebugLineLabel5 = NULL;lv_obj_t *ui_DebugLineLabel6 = NULL;
// event funtions

// build funtions

void ui_ScreenDebug_screen_init(void)
{
ui_ScreenDebug = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenDebug, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_ScreenDebug,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_ScreenDebug, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_ScreenDebug, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ScreenDebug, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container3 = lv_obj_create(ui_ScreenDebug);
lv_obj_remove_style_all(ui_Container3);
lv_obj_set_width( ui_Container3, lv_pct(100));
lv_obj_set_height( ui_Container3, lv_pct(100));
lv_obj_set_align( ui_Container3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container3,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container3, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
lv_obj_clear_flag( ui_Container3, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel, -110 );
lv_obj_set_y( ui_DebugLineLabel, -37 );
lv_obj_set_align( ui_DebugLineLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel,"Debug line 00");
lv_obj_set_style_text_color(ui_DebugLineLabel, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel1 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel1, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel1, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel1, -110 );
lv_obj_set_y( ui_DebugLineLabel1, -37 );
lv_obj_set_align( ui_DebugLineLabel1, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel1,"Debug line 01");
lv_obj_set_style_text_color(ui_DebugLineLabel1, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel2 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel2, -110 );
lv_obj_set_y( ui_DebugLineLabel2, -37 );
lv_obj_set_align( ui_DebugLineLabel2, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel2,"Debug line 02");
lv_obj_set_style_text_color(ui_DebugLineLabel2, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel3 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel3, -110 );
lv_obj_set_y( ui_DebugLineLabel3, -37 );
lv_obj_set_align( ui_DebugLineLabel3, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel3,"Debug line 03");
lv_obj_set_style_text_color(ui_DebugLineLabel3, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel3, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel4 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel4, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel4, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel4, -110 );
lv_obj_set_y( ui_DebugLineLabel4, -37 );
lv_obj_set_align( ui_DebugLineLabel4, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel4,"Debug line 04");
lv_obj_set_style_text_color(ui_DebugLineLabel4, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel4, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel5 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel5, -110 );
lv_obj_set_y( ui_DebugLineLabel5, -37 );
lv_obj_set_align( ui_DebugLineLabel5, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel5,"Debug line 05");
lv_obj_set_style_text_color(ui_DebugLineLabel5, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel5, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_DebugLineLabel6 = lv_label_create(ui_Container3);
lv_obj_set_width( ui_DebugLineLabel6, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_DebugLineLabel6, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_DebugLineLabel6, -110 );
lv_obj_set_y( ui_DebugLineLabel6, -37 );
lv_obj_set_align( ui_DebugLineLabel6, LV_ALIGN_CENTER );
lv_label_set_text(ui_DebugLineLabel6,"Debug line 06");
lv_obj_set_style_text_color(ui_DebugLineLabel6, lv_color_hex(0xF30B29), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_DebugLineLabel6, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

}

void ui_ScreenDebug_screen_destroy(void)
{
   if (ui_ScreenDebug) lv_obj_del(ui_ScreenDebug);

// NULL screen variables
ui_ScreenDebug= NULL;
ui_Container3= NULL;
ui_DebugLineLabel= NULL;
ui_DebugLineLabel1= NULL;
ui_DebugLineLabel2= NULL;
ui_DebugLineLabel3= NULL;
ui_DebugLineLabel4= NULL;
ui_DebugLineLabel5= NULL;
ui_DebugLineLabel6= NULL;

}
