// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_03

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t *ui_Screen3;
extern lv_obj_t *ui_Container3;
extern lv_obj_t *ui_DebugLineLabel;
extern lv_obj_t *ui_DebugLineLabel1;
extern lv_obj_t *ui_DebugLineLabel2;
extern lv_obj_t *ui_DebugLineLabel3;
extern lv_obj_t *ui_DebugLineLabel4;
extern lv_obj_t *ui_DebugLineLabel5;
extern lv_obj_t *ui_DebugLineLabel6;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

