// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project_03

#include "../ui.h"

lv_obj_t *ui_Screen2 = NULL;lv_obj_t *ui_Container1 = NULL;lv_obj_t *ui_LabelSSID = NULL;lv_obj_t *ui_LabelWiFiStatus = NULL;lv_obj_t *ui_BarSignal = NULL;
// event funtions
void ui_event_Screen2( lv_event_t * e) {
    lv_event_code_t event_code = lv_event_get_code(e);

if ( event_code == LV_EVENT_SCREEN_LOADED) {
      _ui_screen_change( &ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 5000, &ui_Screen3_screen_init);
}
}

// build funtions

void ui_Screen2_screen_init(void)
{
ui_Screen2 = lv_obj_create(NULL);
lv_obj_clear_flag( ui_Screen2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_flex_flow(ui_Screen2,LV_FLEX_FLOW_ROW);
lv_obj_set_flex_align(ui_Screen2, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_set_style_bg_color(ui_Screen2, lv_color_hex(0x6E3BDA), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_grad_color(ui_Screen2, lv_color_hex(0x1D0577), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_grad_dir(ui_Screen2, LV_GRAD_DIR_VER, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Container1 = lv_obj_create(ui_Screen2);
lv_obj_remove_style_all(ui_Container1);
lv_obj_set_width( ui_Container1, lv_pct(100));
lv_obj_set_height( ui_Container1, lv_pct(100));
lv_obj_set_align( ui_Container1, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Container1,LV_FLEX_FLOW_COLUMN);
lv_obj_set_flex_align(ui_Container1, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Container1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_pad_row(ui_Container1, 10, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Container1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelSSID = lv_label_create(ui_Container1);
lv_obj_set_width( ui_LabelSSID, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelSSID, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelSSID, -74 );
lv_obj_set_y( ui_LabelSSID, -21 );
lv_obj_set_align( ui_LabelSSID, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelSSID,"SSID: xxxxxx");
lv_obj_set_style_text_color(ui_LabelSSID, lv_color_hex(0xE0DDF3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelSSID, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelSSID, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelWiFiStatus = lv_label_create(ui_Container1);
lv_obj_set_width( ui_LabelWiFiStatus, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelWiFiStatus, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_LabelWiFiStatus, -85 );
lv_obj_set_y( ui_LabelWiFiStatus, -152 );
lv_obj_set_align( ui_LabelWiFiStatus, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelWiFiStatus,"status");
lv_obj_set_style_text_color(ui_LabelWiFiStatus, lv_color_hex(0xE0DDF3), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_LabelWiFiStatus, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_LabelWiFiStatus, &lv_font_montserrat_36, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_BarSignal = lv_bar_create(ui_Container1);
lv_bar_set_value(ui_BarSignal,25,LV_ANIM_OFF);
lv_bar_set_start_value(ui_BarSignal, 0, LV_ANIM_OFF);
lv_obj_set_width( ui_BarSignal, 150);
lv_obj_set_height( ui_BarSignal, 10);
lv_obj_set_align( ui_BarSignal, LV_ALIGN_CENTER );

lv_obj_add_event_cb(ui_Screen2, ui_event_Screen2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
   if (ui_Screen2) lv_obj_del(ui_Screen2);

// NULL screen variables
ui_Screen2= NULL;
ui_Container1= NULL;
ui_LabelSSID= NULL;
ui_LabelWiFiStatus= NULL;
ui_BarSignal= NULL;

}
