// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.6.0
// LVGL version: 8.3.11
// Project name: Uart-SPP_Display_wREST_Project

#ifndef _UART_SPP_DISPLAY_WREST_PROJECT_UI_H
#define _UART_SPP_DISPLAY_WREST_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

    #include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"

///////////////////// SCREENS ////////////////////
#include "screens/ui_ScreenSplash.h"
#include "screens/ui_ScreenClock.h"
#include "screens/ui_ScreenWiFi.h"
#include "screens/ui_ScreenDebug.h"

///////////////////// VARIABLES ////////////////////

// EVENTS
extern lv_obj_t *ui____initial_actions0;

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
